#version 460

#include "xs.glsl"

layout ( binding = 0, set = xs_shader_binding_set_dispatch_m ) uniform dispatch_uniforms_t {
    uvec4 channel_remap;
} dispatch_uniforms;

layout ( binding = 1, set = xs_shader_binding_set_dispatch_m ) uniform texture2D tex_input;
layout ( binding = 2, set = xs_shader_binding_set_dispatch_m ) uniform writeonly image2D img_output;

layout ( binding = 3, set = xs_shader_binding_set_dispatch_m ) uniform sampler linear_sampler;

layout ( local_size_x = 8, local_size_y = 8, local_size_z = 1 ) in;

float map_channel ( vec4 color, uint idx ) {
    uint remap = dispatch_uniforms.channel_remap[idx];
    if ( remap <= 3 ) {
        return color[remap];
    } else if ( remap == 4 ) {
        return 1;
    } else if ( remap == 5 ) {
        return 0;
    } else {
        return 0;
    }
}

void main ( void ) {
    vec2 res = imageSize ( img_output );
    vec2 uv = ( gl_GlobalInvocationID.xy + vec2 ( 0.5 ) ) / res;
    vec4 sample_color = texture ( sampler2D ( tex_input, linear_sampler ), uv );
    vec4 out_color;
    out_color[0] = map_channel ( sample_color, 0 );
    out_color[1] = map_channel ( sample_color, 1 );
    out_color[2] = map_channel ( sample_color, 2 );
    out_color[3] = map_channel ( sample_color, 3 );
    imageStore ( img_output, ivec2 ( gl_GlobalInvocationID.xy ), out_color );
}
