#version 450

#include "xs.glsl"

#include "common.glsl"

layout ( binding = 0, set = xs_shader_binding_set_dispatch_m ) uniform draw_uniforms_t {
    uint face;
    uint sample_count;
    float roughness;
} draw_uniforms;

layout ( binding = 1, set = xs_shader_binding_set_dispatch_m ) uniform textureCube tex_cube_mip0;
layout ( binding = 2, set = xs_shader_binding_set_dispatch_m ) uniform writeonly image2D img_cube;
layout ( binding = 3, set = xs_shader_binding_set_dispatch_m ) uniform sampler sampler_linear;

vec3 ggx_sample ( vec2 e, vec3 wo, vec3 normal, float roughness ) {
    float theta = atan ( roughness * sqrt ( e.x / ( 1.f - e.x ) ) );
    float phi = PI * 2.f * e.y;
    vec3 h = vec3_from_spherical ( theta, phi );

    mat3 tnb = tnb_from_normal ( normal );
    h = normalize ( tnb * h );

    vec3 wi = ( h * dot ( wo, h ) * 2 ) - wo;
    return wi;
}

// Heitz
// http://jcgt.org/published/0007/04/01/paper.pdf
vec3 sampleGGXVNDF(vec3 Ve, float alpha_x, float alpha_y, float U1, float U2)
{
    // Section 3.2: transforming the view direction to the hemisphere configuration
    vec3 Vh = normalize(vec3(alpha_x * Ve.x, alpha_y * Ve.y, Ve.z));
    // Section 4.1: orthonormal basis (with special case if cross product is zero)
    float lensq = Vh.x * Vh.x + Vh.y * Vh.y;
    vec3 T1 = lensq > 0 ? vec3(-Vh.y, Vh.x, 0) / sqrt (lensq) : vec3(1,0,0);
    vec3 T2 = cross(Vh, T1);
    // Section 4.2: parameterization of the projected area
    float r = sqrt(U1);
    float phi = 2.0 * PI * U2;
    float t1 = r * cos(phi);
    float t2 = r * sin(phi);
    float s = 0.5 * (1.0 + Vh.z);
    t2 = (1.0 - s)*sqrt(1.0 - t1*t1) + s*t2;
    // Section 4.3: reprojection onto hemisphere
    vec3 Nh = t1*T1 + t2*T2 + sqrt(max(0.0, 1.0 - t1*t1 - t2*t2))*Vh;
    // Section 3.4: transforming the normal back to the ellipsoid configuration
    vec3 Ne = normalize(vec3(alpha_x * Nh.x, alpha_y * Nh.y, max(0.0, Nh.z)));
    return Ne;
}

vec3 ggx_sample_vndf ( vec2 e, vec3 wo, vec3 normal, float roughness ) {
    mat3 tbn = tbn_from_normal ( normal );
    vec3 view_tangent = normalize ( transpose ( tbn ) * wo );
    vec3 h = sampleGGXVNDF ( view_tangent, roughness, roughness, e.x, e.y );
    h = normalize ( tbn * h );
    vec3 wi = ( h * dot ( wo, h ) * 2 ) - wo;
    return wi;
}

// https://github.com/eliemichel/LearnWebGPU-Code/blob/step222/resources/compute-shader.wgsl
vec3 cubemap_direction ( uint face, vec2 uv ) {
    float sc = uv.x * 2.f - 1.f;
    float tc = uv.y * 2.f - 1.f;

    vec3 dir = vec3 ( 0 );
    switch ( face ) {
    case 0:
        dir = vec3 ( 1.f, -tc, -sc );
        break;
    case 1:
        dir = vec3 ( -1.f, -tc, sc );
        break;
    case 2:
        dir = vec3 ( sc, 1.f, tc );
        break;
    case 3:
        dir = vec3 ( sc, -1.f, -tc );
        break;
    case 4:
        dir = vec3 ( sc, -tc, 1.f );
        break;
    case 5:
        dir = vec3 ( -sc, -tc, -1.f );
        break;
    }

    return normalize ( dir );
}

layout ( local_size_x = 8, local_size_y = 8, local_size_z = 1 ) in;
void main ( void ) {
    vec2 resolution = imageSize ( img_cube );
    vec2 screen_uv = ( vec2 ( gl_GlobalInvocationID.xy ) + vec2 ( 0.5 ) ) / resolution;
    vec3 dir = cubemap_direction ( draw_uniforms.face, screen_uv );

    // see Real Shading in Unreal Engine 4
    vec3 world_normal = dir;
    vec3 world_view = dir;

    vec3 total_radiance = vec3 ( 0 );
    float total_weight = 0.f;
    rng_wang_state_t rng_state = rng_wang_init ( gl_GlobalInvocationID.xy );
    uint sample_count = draw_uniforms.sample_count;
    float roughness = draw_uniforms.roughness;
    for ( uint i = 0; i < sample_count; ++i ) {
        float ex = rng_wang ( rng_state );
        float ey = rng_wang ( rng_state );
        vec2 e2 = vec2 ( ex, ey );
        vec3 wi = ggx_sample_vndf ( e2, world_view, world_normal, roughness );
    
        float nl = clamp ( dot ( world_normal, wi ), 0, 1 );
        vec3 radiance = texture ( samplerCube ( tex_cube_mip0, sampler_linear ), wi ).xyz;
        total_radiance += radiance;
        total_weight += nl;
    }

    vec3 color = total_radiance / total_weight;
    imageStore ( img_cube, ivec2 ( gl_GlobalInvocationID.xy ), vec4 ( color, 1 ) );
}
