#version 460

#include "xs.glsl"
#include "common.glsl"

layout ( binding = 0, set = xs_shader_binding_set_dispatch_m ) uniform texture2D tex_radiance;
layout ( binding = 1, set = xs_shader_binding_set_dispatch_m ) uniform writeonly image2D img_irradiance;
layout ( binding = 2, set = xs_shader_binding_set_dispatch_m ) uniform sampler sampler_linear;

layout ( local_size_x = 8, local_size_y = 8, local_size_z = 1 ) in;
void main () {
    vec2 screen_uv = vec2 ( ( gl_GlobalInvocationID.xy + vec2 ( 0.5 ) ) / vec2 ( imageSize ( img_irradiance ) ) );
    vec2 spherical = spherical_from_uv ( screen_uv );
    vec3 dir = vec3_from_spherical ( spherical.x, spherical.y );

    mat3 tnb = tnb_from_normal ( dir );

    vec3 irradiance = vec3 ( 0 );
    int sample_count = 0;
    float sample_step = 0.025;

    for ( float phi = 0; phi < 2.0 * PI; phi += sample_step ) {
        for ( float theta = 0; theta < 0.5 * PI; theta += sample_step ) {
            vec3 sample_tangent = vec3_from_spherical ( theta, phi );
            vec3 sample_world = tnb * sample_tangent;
            vec2 sample_uv = equirectangular_uv_from_dir ( sample_world );
            irradiance += texture ( sampler2D ( tex_radiance, sampler_linear ), sample_uv ).rgb * cos ( theta ) * sin ( theta );
            sample_count += 1;
        }
    }

    irradiance = irradiance * PI / float ( sample_count );
    imageStore ( img_irradiance, ivec2 ( gl_GlobalInvocationID.xy ), vec4 ( irradiance, 1 ) );
}
