#version 450

#include "xs.glsl"

#include "common.glsl"
#include "ibl_split_sum.glsl"

layout ( binding = 0, set = xs_shader_binding_set_dispatch_m ) uniform draw_uniforms_t {
    uint face;
    uint sample_count;
    float roughness;
} draw_uniforms;

layout ( binding = 1, set = xs_shader_binding_set_dispatch_m ) uniform textureCube tex_cube_mip0;
layout ( binding = 2, set = xs_shader_binding_set_dispatch_m ) uniform writeonly image2D img_cube;
layout ( binding = 3, set = xs_shader_binding_set_dispatch_m ) uniform sampler sampler_linear;

// https://github.com/eliemichel/LearnWebGPU-Code/blob/step222/resources/compute-shader.wgsl
vec3 cubemap_direction ( uint face, vec2 uv ) {
    float sc = uv.x * 2.f - 1.f;
    float tc = uv.y * 2.f - 1.f;

    vec3 dir = vec3 ( 0 );
    switch ( face ) {
    case 0:
        dir = vec3 ( 1.f, -tc, -sc );
        break;
    case 1:
        dir = vec3 ( -1.f, -tc, sc );
        break;
    case 2:
        dir = vec3 ( sc, 1.f, tc );
        break;
    case 3:
        dir = vec3 ( sc, -1.f, -tc );
        break;
    case 4:
        dir = vec3 ( sc, -tc, 1.f );
        break;
    case 5:
        dir = vec3 ( -sc, -tc, -1.f );
        break;
    }

    return normalize ( dir );
}

layout ( local_size_x = 8, local_size_y = 8, local_size_z = 1 ) in;
void main ( void ) {
    vec2 resolution = imageSize ( img_cube );
    vec2 screen_uv = ( vec2 ( gl_GlobalInvocationID.xy ) + vec2 ( 0.5 ) ) / resolution;
    vec3 dir = cubemap_direction ( draw_uniforms.face, screen_uv );

    // see "Real Shading in Unreal Engine 4" paper
    vec3 world_normal = dir;
    vec3 world_view = dir;

    vec3 total_radiance = vec3 ( 0 );
    float total_weight = 0.f;
    uint sample_count = draw_uniforms.sample_count;
    float roughness = draw_uniforms.roughness;
    for ( uint i = 0; i < sample_count; ++i ) {
        vec2 e2 = rng_hammersley ( i, sample_count );
        vec3 wi = ggx_sample_wi ( e2, world_view, world_normal, roughness );
    
        float nl = clamp ( dot ( world_normal, wi ), 0, 1 );
        vec3 radiance = texture ( samplerCube ( tex_cube_mip0, sampler_linear ), wi ).xyz;
        total_radiance += radiance;
        total_weight += nl;
    }

    vec3 color = total_radiance / total_weight;
    imageStore ( img_cube, ivec2 ( gl_GlobalInvocationID.xy ), vec4 ( color, 1 ) );
}
