#version 450

#include "xs.glsl"

#include "common.glsl"
#include "ibl_split_sum.glsl"

layout ( binding = 0, set = xs_shader_binding_set_dispatch_m ) uniform uniform_buffer_t {
    uint sample_count;
} draw_uniforms;

layout ( binding = 1, set = xs_shader_binding_set_dispatch_m, r11f_g11f_b10f ) uniform writeonly image2D img_lut;

float ggx_g_shlick ( float nv, float roughness ) {
    float a = roughness;
    float k = ( a * a ) / 2.0;

    float nom = nv;
    float denom = nv * (1.0 - k) + k;

    return nom / denom;
}

float ggx_g (vec3 n, vec3 v, vec3 l, float roughness) {
    float nv = max ( dot ( n, v ), 0.f );
    float nl = max ( dot ( n, l ), 0.f );
    float ggx1 = ggx_g_shlick ( nl, roughness );
    float ggx2 = ggx_g_shlick ( nv, roughness );

    return ggx1 * ggx2;
}

layout ( local_size_x = 8, local_size_y = 8, local_size_z = 1 ) in;
void main ( void ) {
    ivec2 resolution = imageSize ( img_lut );
    vec2 screen_uv = vec2 ( ( gl_GlobalInvocationID.xy + vec2 ( 0.5 ) ) / vec2 ( resolution ) );

    // see "Real Shading in Unreal Engine 4" paper
    float nv = screen_uv.x;
    float roughness = screen_uv.y;

    vec3 v = vec3 ( sqrt ( 1.f - nv * nv ), 0, nv ); // sin, 0, cos
    vec3 n = vec3 ( 0, 0, 1 );

    float sum_a = 0;
    float sum_b = 0;
    uint sample_count = 1024;
    for ( uint i = 0; i < sample_count; ++i ) {
        vec2 e2 = rng_hammersley ( i, sample_count );
        vec3 h = ggx_sample_h ( e2, v, n, roughness );
        vec3 wi = ( h * dot ( v, h ) * 2 ) - v;
        float nl = clamp ( wi.z, 0, 1 );
        float nh = clamp ( h.z, 0, 1 );
        float vh = clamp ( dot ( v, h ), 0, 1 );
        if ( nl > 0 ) {
            float v = ggx_g ( n, v, wi, roughness );
            float g = v * vh / ( nh * nv );
            float f_c = pow ( 1.0 - vh, 5 );

            sum_a += ( 1.f - f_c ) * g;
            sum_b += f_c * g;
        }
    }

    vec2 result = vec2 ( sum_a, sum_b ) / float ( sample_count );
    imageStore ( img_lut, ivec2 ( gl_GlobalInvocationID.xy ), vec4 ( result, 0, 1 ) );
}
