#version 460

#include "xs.glsl"
#include "common.glsl"

layout ( binding = 0, set = xs_shader_binding_set_dispatch_m ) uniform draw_uniforms_t {
    vec2 resolution_f32;
    uint hiz_mip_count;
} draw_uniforms;

layout ( binding = 1, set = xs_shader_binding_set_dispatch_m ) uniform texture2D tex_normal;
layout ( binding = 2, set = xs_shader_binding_set_dispatch_m ) uniform texture2D tex_base_color;
layout ( binding = 3, set = xs_shader_binding_set_dispatch_m ) uniform texture2D tex_lighting;
layout ( binding = 4, set = xs_shader_binding_set_dispatch_m ) uniform texture2D tex_hiz;

layout ( binding = 5, set = xs_shader_binding_set_dispatch_m ) uniform writeonly image2D img_color;

layout ( binding = 6, set = xs_shader_binding_set_dispatch_m ) uniform sampler sampler_linear;

layout ( local_size_x = 8, local_size_y = 8, local_size_z = 1 ) in;

// GTAO
// https://www.activision.com/cdn/research/Practical_Real_Time_Strategies_for_Accurate_Indirect_Occlusion_NEW%20VERSION_COLOR.pdf
// https://github.com/GameTechDev/XeGTAO
float gtao ( rng_wang_state_t rng_state, vec2 screen_uv ) {
    float depth = textureLod ( sampler2D ( tex_hiz, sampler_linear ), screen_uv, 0 ).x;
    if ( proj_depth_is_out ( depth ) ) {
        return 0;
    }
    vec3 position = view_from_depth ( screen_uv, depth );
    vec3 normal = normalize ( texture ( sampler2D ( tex_normal, sampler_linear ), screen_uv ).xyz * 2 - 1 );
    vec3 view = normalize ( -position );

    // constants
    float sample_distribution_power = 2;
    float thin_occluder_compensation = 0;
    float effect_radius = 0.58f * 1.457f;
    float effect_falloff_range = 0.615f;
    float falloff_range = effect_falloff_range * effect_radius;
    float final_value_power = 2.2;

    float falloff_from = effect_radius * ( 1 - effect_falloff_range );
    float falloff_mul = -1 / falloff_range;
    float falloff_add = falloff_from / falloff_range + 1.0;

    float visibility = 0;

    // noise
    float slice_noise = rng_wang ( rng_state );
    float sample_noise = rng_wang ( rng_state );

    float pixel_too_close_threshold = 1.3;
    vec2 uv_pixel_size = 1.0.xx / frame_uniforms.resolution_f32;
    vec3 view_offsetted_pos = view_from_depth ( screen_uv + uv_pixel_size, depth );
    vec2 view_pixel_size = view_offsetted_pos.xy - position.xy;
    float screen_radius = effect_radius / view_pixel_size.x;
    float min_s = pixel_too_close_threshold / screen_radius;

    visibility += clamp ( ( 10 - screen_radius ) / 100, 0, 1 ) * 0.5;

    int gtao_slice_count = 3;
    for ( int slice_it = 0; slice_it < gtao_slice_count; ++slice_it ) {
        float slice_k = ( slice_it + slice_noise ) / gtao_slice_count;
        float phi = slice_k * PI;
        float cos_phi = cos ( phi );
        float sin_phi = sin ( phi );
        vec2 omega = vec2 ( cos_phi, -sin_phi );

        omega *= screen_radius;

        vec3 direction = vec3 ( cos_phi, sin_phi, 0 );
        vec3 ortho_direction = direction - dot ( direction, view ) * view;
        vec3 axis = normalize ( cross ( direction, view ) );
        vec3 proj_normal = normal - dot ( normal, axis ) * axis;
        float sign_norm = sign ( dot ( ortho_direction, proj_normal ) );
        float proj_normal_len = length ( proj_normal );
        float cos_norm = clamp ( dot ( proj_normal, view ) / proj_normal_len, 0, 1 );
        float n = sign_norm * acos ( cos_norm );

        float low_horizon_cos_0 = cos ( n + PI / 2 );
        float low_horizon_cos_1 = cos ( n - PI / 2 );

        float horizon_cos_0 = low_horizon_cos_0;
        float horizon_cos_1 = low_horizon_cos_1;

        int gtao_steps_per_slice = 3;
        for ( int step_it = 0; step_it < gtao_steps_per_slice; ++step_it ) {
            float step_base_noise = float ( slice_it + step_it * gtao_steps_per_slice ) * 0.6180339887498948482;
            float step_noise = fract ( sample_noise + step_base_noise );

            float s = ( step_it + step_noise ) / gtao_steps_per_slice;
            s = pow ( s, sample_distribution_power );
            s += min_s;

            vec2 sample_offset = s * omega;
            float sample_offset_len = length ( sample_offset );

            float mip_level = 0;

            sample_offset = round ( sample_offset ) * uv_pixel_size;

            vec2 sample_uv_0 = screen_uv + sample_offset;
            float sample_depth_0 = textureLod ( sampler2D ( tex_hiz, sampler_linear ), sample_uv_0, mip_level ).x;
            vec3 sample_pos_0 = view_from_depth ( sample_uv_0, sample_depth_0 );

            vec2 sample_uv_1 = screen_uv - sample_offset;
            float sample_depth_1 = textureLod ( sampler2D ( tex_hiz, sampler_linear ), sample_uv_1, mip_level ).x;
            vec3 sample_pos_1 = view_from_depth ( sample_uv_1, sample_depth_1 );

            vec3 sample_delta_0 = sample_pos_0 - position;
            vec3 sample_delta_1 = sample_pos_1 - position;

            float sample_dist_0 = length ( sample_delta_0 );
            float sample_dist_1 = length ( sample_delta_1 );

            vec3 sample_horizon_0 = sample_delta_0 / sample_dist_0;
            vec3 sample_horizon_1 = sample_delta_1 / sample_dist_1;

            float falloff_base_0 = length ( vec3 ( sample_delta_0.xy, sample_delta_0.z * ( 1 + thin_occluder_compensation ) ) );
            float falloff_base_1 = length ( vec3 ( sample_delta_1.xy, sample_delta_0.z * ( 1 + thin_occluder_compensation ) ) );
            float weight_0 = clamp ( falloff_base_0 * falloff_mul + falloff_add, 0, 1 );
            float weight_1 = clamp ( falloff_base_1 * falloff_mul + falloff_add, 0, 1 );

            float shc_0 = dot ( sample_horizon_0, view );
            float shc_1 = dot ( sample_horizon_1, view );

            shc_0 = mix ( low_horizon_cos_0, shc_0, weight_0 );
            shc_1 = mix ( low_horizon_cos_1, shc_1, weight_1 );

            horizon_cos_0 = max ( horizon_cos_0, shc_0 );
            horizon_cos_1 = max ( horizon_cos_1, shc_1 );
        }

        // proj_normal_len = lerp

        float h_0 = -acos ( horizon_cos_1 );
        float h_1 = acos ( horizon_cos_0 );

        float iarc_0 = ( cos_norm + 2.0 * h_0 * sin ( n ) - cos ( 2 * h_0 - n ) ) / 4;
        float iarc_1 = ( cos_norm + 2.0 * h_1 * sin ( n ) - cos ( 2 * h_1 - n ) ) / 4;
        float local_visibility = proj_normal_len * ( iarc_0 + iarc_1 );
        visibility += local_visibility;
    }

    visibility /= gtao_slice_count;
    visibility = pow ( visibility, final_value_power );
    visibility = max ( 0.03, visibility );

    return visibility;
}

// https://arxiv.org/pdf/2301.11376
// https://cdrinmatane.github.io/posts/ssaovb-code/
// https://github.com/cdrinmatane/SSRT3
#define SECTOR_COUNT 32
uint ssilvb_update_sectors ( float minHorizon, float maxHorizon, uint globalOccludedBitfield)
{
    uint startHorizonInt = uint ( minHorizon * SECTOR_COUNT );
    uint angleHorizonInt = uint ( ceil((maxHorizon-minHorizon) * SECTOR_COUNT) );
    uint angleHorizonBitfield = angleHorizonInt > 0 ? ( uint ( 0xFFFFFFFF ) >> (SECTOR_COUNT-angleHorizonInt)) : 0;
    uint currentOccludedBitfield = angleHorizonBitfield << startHorizonInt;
    return globalOccludedBitfield | currentOccludedBitfield;
}

uint ssilvb_make_bitmask ( float minHorizon, float maxHorizon ) {
    uint startHorizonInt = uint ( minHorizon * SECTOR_COUNT );
    uint angleHorizonInt = uint ( ceil((maxHorizon-minHorizon) * SECTOR_COUNT) );
    uint angleHorizonBitfield = angleHorizonInt > 0 ? ( uint ( 0xFFFFFFFF ) >> (SECTOR_COUNT-angleHorizonInt)) : 0;
    uint currentOccludedBitfield = angleHorizonBitfield << startHorizonInt;
    return currentOccludedBitfield;
}

vec3 ssilvb_horizon_sample ( bool forward_dir, vec3 position, vec2 sample_uv, vec3 view, vec3 normal, float n, inout uint occlusion_bitfield, out bool is_out ) {
    if ( is_outside_screen ( sample_uv ) ) {
        is_out = true;
        return vec3 ( 0 );
    }

    float sample_depth = textureLod ( sampler2D ( tex_hiz, sampler_linear ), sample_uv, 0 ).x;
    
    if ( proj_depth_is_out ( sample_depth ) ) {
        is_out = true;
        return vec3 ( 0 );
    }

    vec3 sample_pos = view_from_depth ( sample_uv, sample_depth );
    vec3 sample_normal = normalize ( texture ( sampler2D ( tex_normal, sampler_linear ), sample_uv ).xyz * 2 - 1 );
    vec3 sample_light = textureLod ( sampler2D ( tex_lighting, sampler_linear ), sample_uv, 4 ).xyz;

    vec3 sample_delta = sample_pos - position;

    float ssilvb_thickness = 0.5;

    vec2 sampling_dir = forward_dir ? vec2 ( 1, 1 ) : -vec2 ( 1, 1 );
    vec3 sample_delta_backface = sample_delta - view * ssilvb_thickness;
    vec2 front_back_horizon = vec2 ( dot ( normalize ( sample_delta ), view ), dot ( normalize ( sample_delta_backface ), view ) );
    front_back_horizon = acos ( clamp ( front_back_horizon, -1, 1 ) );
    front_back_horizon = clamp ( ( sampling_dir * -front_back_horizon + n + PI / 2 ) / PI, 0, 1 );
    front_back_horizon = forward_dir ? front_back_horizon.yx : front_back_horizon.xy;
    uint bitfield = ssilvb_make_bitmask ( front_back_horizon.x, front_back_horizon.y );
    vec3 lighting = vec3 ( float ( bitCount ( bitfield & ~occlusion_bitfield ) ) / float ( SECTOR_COUNT ) );
    lighting = sample_light;
    lighting *= clamp ( dot ( normal, normalize ( sample_delta ) ), 0, 1 );
    lighting *= clamp ( dot ( sample_normal, -normalize ( sample_delta ) ), 0, 1 );
    occlusion_bitfield |= bitfield;

    is_out = false;
    return lighting;
}

vec4 ssilvb ( inout rng_wang_state_t rng_state, vec2 screen_uv ) {
    float depth = textureLod ( sampler2D ( tex_hiz, sampler_linear ), screen_uv, 0 ).x;
    if ( proj_depth_is_out ( depth ) ) {
        return vec4 ( 0 );
    }
    vec3 position = view_from_depth ( screen_uv, depth );
    vec3 normal = normalize ( texture ( sampler2D ( tex_normal, sampler_linear ), screen_uv ).xyz * 2 - 1 );
    vec3 view = normalize ( -position );

    // constants
    float sample_distribution_power = 2;
    float thin_occluder_compensation = 0;
    float effect_radius = 4;
    float final_value_power = 2.2;

    float visibility = 0;
    vec3 lighting = vec3 ( 0 );

    // noise
    float slice_noise = rng_wang ( rng_state );
    float sample_noise = rng_wang ( rng_state );

    float pixel_too_close_threshold = 1.3;
    vec2 uv_pixel_size = 1.0.xx / frame_uniforms.resolution_f32;
    vec3 view_offsetted_pos = view_from_depth ( screen_uv + uv_pixel_size, depth );
    vec2 view_pixel_size = view_offsetted_pos.xy - position.xy;
    float screen_radius = effect_radius / view_pixel_size.x;
    float min_s = pixel_too_close_threshold / screen_radius;

    visibility += clamp ( ( 10 - screen_radius ) / 100, 0, 1 ) * 0.5;

    int sample_count = 0;
    int slice_count = 3;
    for ( int slice_it = 0; slice_it < slice_count; ++slice_it ) {
        float slice_k = ( slice_it + slice_noise ) / slice_count;
        float phi = slice_k * PI;
        float cos_phi = cos ( phi );
        float sin_phi = sin ( phi );
        vec2 omega = vec2 ( cos_phi, -sin_phi );

        omega *= screen_radius;

        vec3 direction = vec3 ( cos_phi, sin_phi, 0 );
        vec3 ortho_direction = direction - dot ( direction, view ) * view;
        vec3 axis = normalize ( cross ( direction, view ) );
        vec3 proj_normal = normal - dot ( normal, axis ) * axis;
        float sign_norm = sign ( dot ( ortho_direction, proj_normal ) );
        float proj_normal_len = length ( proj_normal );
        float cos_norm = clamp ( dot ( proj_normal, view ) / proj_normal_len, 0, 1 );
        float n = sign_norm * acos ( cos_norm );

        uint bitfield = 0;

        int steps_per_slice = 3;
        for ( int step_it = 0; step_it < steps_per_slice; ++step_it ) {
            float step_base_noise = float ( slice_it + step_it * steps_per_slice ) * 0.6180339887498948482;
            float step_noise = fract ( sample_noise + step_base_noise );

            float s = ( step_it + step_noise ) / steps_per_slice;
            s = pow ( s, sample_distribution_power );
            s += min_s;

            vec2 sample_offset = s * omega;
            float sample_offset_len = length ( sample_offset );

            float mip_level = 0;

            sample_offset = round ( sample_offset ) * uv_pixel_size;

            bool sample_fail;
            lighting += ssilvb_horizon_sample ( true, position, screen_uv + sample_offset, view, normal, n, bitfield, sample_fail );
            if ( ! sample_fail ) sample_count += 1;
            
            lighting += ssilvb_horizon_sample ( false, position, screen_uv - sample_offset, view, normal, n, bitfield, sample_fail );
            if ( ! sample_fail ) sample_count += 1;
        }

        // proj_normal_len = lerp

        visibility += 1.0 - ( float ( bitCount ( bitfield ) ) / float ( SECTOR_COUNT ) );
    }

    visibility /= slice_count;
    visibility = pow ( visibility, final_value_power );
    visibility = max ( 0.03, visibility );

    lighting /= slice_count;

    //lighting = lighting * 3 * 2 / sample_count;

    return vec4 ( lighting, visibility );
}

// alternative implementation from: https://cybereality.com/screen-space-indirect-lighting-with-visibility-bitmask-improvement-to-gtao-ssao-real-time-ambient-occlusion-algorithm-glsl-shader-implementation/
const uint sector_count = 32u;
uint make_bitmask ( float min_horizon, float max_horizon ) {
    uint start_bit = uint ( min_horizon * float ( sector_count ) );
    uint horizon_angle = uint ( ceil ( ( max_horizon - min_horizon ) * float ( sector_count ) ) );
    uint angle_bits = horizon_angle > 0 ? uint ( 0xffffffff >> ( sector_count - horizon_angle ) ) : 0;
    uint bitmask = angle_bits << start_bit;
    return bitmask;
}

vec4 ssilvb2 ( inout rng_wang_state_t rng_state, vec2 screen_uv ) {
    float sample_count = 4;
    float sample_radius = 4;
    float slice_count = 2;
    float hit_thickness = 0.5;

    uint indirect = 0;
    uint occlusion = 0;
    float visibility = 0;
    vec3 lighting = vec3 ( 0 );

    vec2 aspect = draw_uniforms.resolution_f32.yx / draw_uniforms.resolution_f32.x;

    float depth = textureLod ( sampler2D ( tex_hiz, sampler_linear ), screen_uv, 0 ).x;
    vec3 position = view_from_depth ( screen_uv, depth );
    vec3 view = normalize ( -position );
    vec3 normal = normalize ( texture ( sampler2D ( tex_normal, sampler_linear ), screen_uv ).xyz * 2 - 1 );
    float slice_rotation = 2 * PI / slice_count;
    float sample_scale = ( -sample_radius * frame_uniforms.proj_from_view[0][0] ) / position.z;
    float sample_offset = 0.5 * rng_wang ( rng_state );
    float jitter = rng_wang ( rng_state ) - 0.5;

    for ( float slice = 0.0; slice < slice_count; slice += 1.0 ) {
        float phi = slice_rotation * ( slice + jitter ) + PI;
        vec2 omega = vec2 ( cos ( phi ), sin ( phi ) );
        vec3 direction = vec3 ( omega.x, omega.y, 0.0 );
        vec3 ortho_direction = direction - dot ( direction, view ) * view;
        vec3 axis = cross ( direction, view );
        vec3 proj_normal = normal - dot ( normal, axis ) * axis;
        float proj_length = length ( proj_normal );

        float sign_n = sign ( dot ( ortho_direction, proj_normal ) );
        float cos_n = clamp ( dot ( proj_normal, view ) / proj_length, 0.0, 1.0 );
        float n = sign_n * acos ( cos_n );

        for ( float current_sample = 0.0; current_sample < sample_count; current_sample += 1.0 ) {
            float sample_step = ( current_sample + jitter ) / sample_count + sample_offset;
            vec2 sample_uv = screen_uv - sample_step * sample_scale * omega * aspect;
            
            if ( is_outside_screen ( sample_uv ) ) {
                continue;
            }

            float sample_depth = textureLod ( sampler2D ( tex_hiz, sampler_linear ), sample_uv, 0 ).x;
            vec3 sample_position = view_from_depth ( sample_uv, sample_depth );
            vec3 sample_normal = normalize ( texture ( sampler2D ( tex_normal, sampler_linear ), sample_uv ).xyz * 2 - 1 );
            vec3 sample_light = textureLod ( sampler2D ( tex_lighting, sampler_linear ), sample_uv, 7 ).xyz;
            vec3 sample_distance = sample_position - position;
            float sample_length = length ( sample_distance );
            vec3 sample_horizon = sample_distance / sample_length;

            vec2 front_back_horizon;
            front_back_horizon.x = dot ( sample_horizon, view );
            front_back_horizon.y = dot ( normalize ( sample_distance - view * hit_thickness ), view );
            front_back_horizon = acos ( front_back_horizon );
            front_back_horizon = clamp ( ( front_back_horizon + n + PI / 2 ) / PI, 0.0, 1.0 );

            indirect = make_bitmask ( front_back_horizon.x, front_back_horizon.y );
            lighting += ( 1.0 - float ( bitCount ( indirect & ~occlusion ) ) / float ( sector_count ) ) * sample_light 
                * clamp ( dot ( normal, sample_horizon ), 0.0, 1.0 ) * clamp ( dot ( sample_normal, -sample_horizon ), 0.0, 1.0 );
            occlusion |= indirect;
        }

        visibility += 1.0 - float ( bitCount ( occlusion ) ) / float ( sector_count );
    }

    visibility /= slice_count;
    lighting /= slice_count;

    return vec4 ( lighting, visibility );
}

vec4 ssrt ( inout rng_wang_state_t rng_state, vec2 screen_uv ) {
    // sample
    vec3 view_normal = texture ( sampler2D ( tex_normal, sampler_linear ), screen_uv ).xyz * 2 - 1;
    float depth = textureLod ( sampler2D ( tex_hiz, sampler_linear ), screen_uv, 0 ).x;
    vec3 base_color = texture ( sampler2D ( tex_base_color, sampler_linear ), screen_uv ).xyz;

    view_normal = normalize ( view_normal );

    // reconstruct position
    vec3 view_pos = view_from_depth ( screen_uv, depth );

#define SSRT_RAY_COUNT 4

    // init accumulators
    float sample_distances[SSRT_RAY_COUNT];
    vec3 sample_colors[SSRT_RAY_COUNT];

    for ( uint ray_it = 0; ray_it < SSRT_RAY_COUNT; ++ray_it ) {
        sample_colors[ray_it] = vec3 ( 0, 0, 0 );
        sample_distances[ray_it] = 1;
    }

    float ex = rng_wang ( rng_state );
    float ey = rng_wang ( rng_state );

    vec3 hemisphere_normal;
    vec3 hit_normal;

    vec3 sample_color = vec3 ( 0, 0, 0 );

    if ( !proj_depth_is_out ( depth ) ) {
        for ( uint ray_it = 0; ray_it < SSRT_RAY_COUNT; ++ray_it ) {
            // sample hemisphere
            vec2 e2 = vec2 ( ex, ey );
            hemisphere_normal = sample_cosine_weighted_hemisphere_normal ( e2, view_normal );
            hemisphere_normal = normalize ( hemisphere_normal ); // bias towards normal to reduce hiz self intersections

            // trace
            vec3 hit_screen_pos;
            float hit_depth;
            bool hit;

            hit = trace_screen_space_ray ( hit_screen_pos, hit_depth, view_pos + view_normal * 0.01, hemisphere_normal, tex_hiz, draw_uniforms.hiz_mip_count, sampler_linear, 50, 0.5 ); 

            if ( hit ) {
                vec3 hit_lighting = textureLod ( sampler2D ( tex_lighting, sampler_linear ), hit_screen_pos.xy, 5 ).xyz;
                vec3 hit_view_pos = view_from_depth ( hit_screen_pos.xy, hit_depth );
                float hit_distance = distance ( view_pos, hit_view_pos );
                //float incoming_radiance = max ( dot ( hit_normal, -hemisphere_normal ), 0 ); // Approximate with a simple NdotL...
                sample_colors[ray_it] = hit_lighting;// * max ( dot ( view_normal, hemisphere_normal ), 0 );// * incoming_radiance;
                sample_distances[ray_it] = hit_distance;
            }
        }
    }

    for ( uint ray_it = 0; ray_it < SSRT_RAY_COUNT; ++ray_it ) {
        float d = sample_distances[ray_it];
        float attenuation = 1;
        //attenuation = 1 / ( d * d + 1 );
        //float attenuation = ( d * d ) / ( ( d * d + 0.1 ) * ( d * d + 0.1 ) );
        //float occlusion = min ( 1.0, sample_distances[ray_it] );
        //if ( d < 0.01 ) attenuation = 0;
        sample_color += sample_colors[ray_it] * base_color * attenuation;// * occlusion;// * attenuation * attenuation;
    }

    sample_color /= float ( SSRT_RAY_COUNT );
    return vec4 ( sample_color,  1 );
}

void main ( void ) {
    vec2 screen_uv = vec2 ( ( gl_GlobalInvocationID.xy + vec2 ( 0.5 ) ) / draw_uniforms.resolution_f32 );
    vec3 base_color = texture ( sampler2D ( tex_base_color, sampler_linear ), screen_uv ).xyz;
    rng_wang_state_t rng_state = rng_wang_init ( gl_GlobalInvocationID.xy );
    vec4 gi_ao = ssilvb ( rng_state, screen_uv );
    vec3 out_color = gi_ao.xyz * base_color * gi_ao.w;
    imageStore ( img_color, ivec2 ( gl_GlobalInvocationID.xy ), vec4 ( out_color, 1 ) );
}
