#version 450

#include "xs.glsl"
#include "common.glsl"

#include "tessellation_common.glsl"

#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_debug_printf : enable

//
// GPU Zen 2 - Adaptive GPU Tessellation with Compute Shaders
//

struct vertex_t {
    float pos[3];
};

layout ( binding = 0, set = xs_shader_binding_set_dispatch_m, scalar ) buffer readonly vertex_buffer_t {
    vertex_t data[];
} vertex_buffer;

layout ( binding = 1, set = xs_shader_binding_set_dispatch_m ) buffer readonly index_buffer_t {
    uint data[];
} index_buffer;

layout ( binding = 2, set = xs_shader_binding_set_dispatch_m ) buffer readonly prev_subdivision_buffer_t {
    uint count;
    uint _pad0[3];
    uvec2 data[];
} prev_subdivision_buffer;

layout ( binding = 3, set = xs_shader_binding_set_dispatch_m ) buffer subdivision_buffer_t {
    uint count;
    uint _pad0[3];
    uvec2 data[];
} subdivision_buffer;

layout ( binding = 4, set = xs_shader_binding_set_dispatch_m ) buffer culled_subdivision_buffer_t {
    uint count;
    uint _pad0[3];
    uvec2 data[];
} culled_subdivision_buffer;

mat3 bit_to_xform ( uint bit ) {
    float s = float ( bit ) - 0.5;
    vec3 c1 = vec3 ( -0.5,   -s, 0 ); 
    vec3 c2 = vec3 (    s, -0.5, 0 ); 
    vec3 c3 = vec3 (  0.5,  0.5, 1 );
    return mat3 ( c1, c2, c3 );
}

mat3 key_to_xform ( uint key ) {
    mat3 xform = mat3 ( 1.0 );
    
    while ( key > 1 ) {
        xform = bit_to_xform ( key & 1 ) * xform;
        key = key >> 1;
    }

    return xform;
}

vec3 berp ( vec3 v[3], vec2 u ) {
    return v[0] + u.x * ( v[1] - v[0] ) + u.y * ( v[2] - v[0] );
}

void build_key_verts ( uint key, vec3 prim_verts[3], out vec3 out_verts[3] ) {
    mat3 xform = key_to_xform ( key );

    vec2 u1 = ( xform * vec3 ( 0, 0, 1 ) ).xy;
    vec2 u2 = ( xform * vec3 ( 0, 1, 1 ) ).xy;
    vec2 u3 = ( xform * vec3 ( 1, 0, 1 ) ).xy;

    out_verts[0] = berp ( prim_verts, u1 );
    out_verts[1] = berp ( prim_verts, u2 );
    out_verts[2] = berp ( prim_verts, u3 );
}

vec3 load_vec3 ( float[3] f32 ) {
    return vec3 ( f32[0], f32[1], f32[2] );
}

vec3 load_vert ( uint vert_id ) {
    uint idx = index_buffer.data[vert_id];
    float[3] pos = vertex_buffer.data[idx].pos;
    return load_vec3 ( pos );
}

void build_prim_verts ( uint prim_id, out vec3 out_verts[3] ) {
    out_verts[0] = load_vert ( prim_id * 3 + 0 );
    out_verts[1] = load_vert ( prim_id * 3 + 1 );
    out_verts[2] = load_vert ( prim_id * 3 + 2 );
}

float compute_lod ( vec2 subdivision, float distance_to_camera, float prim_world_size ) {
    // image plane size at given distance
    float img_plane_size = 2 * tan ( frame_uniforms.fov_y / 2 ) * distance_to_camera;
    // how many pixels per unit size at given distance
    float screen_scale = frame_uniforms.resolution_f32.y / img_plane_size;
    //float prim_world_size = 10.0;
    // pixel size of primitive triangle side    
    float prim_pixel_size = prim_world_size * screen_scale;
    float target_pixel_size = 10.0;
    float s = target_pixel_size / prim_pixel_size;
    // doubled because side size is halved every 2 lod levels
    float lod = -log2 ( s ) * 2;
    lod = clamp ( lod, 0, 30 );
    return lod;
}

bool is_leaf_key ( uint key ) {
    return findMSB ( key ) == 31;
}

bool is_root_key ( uint key ) {
    return key == 1;
}

bool is_child_zero_key ( uint key ) {
    return ( key & 1 ) == 0;
}

uint make_parent_key ( uint key ) {
    return key >> 1;
}

uvec2 make_children_keys ( uint key ) {
    return uvec2 ( ( key << 1 ) | 0, ( key << 1 ) | 1 );
}

bool cull_subdivision ( uvec2 subdivision ) {
    uint prim_id = subdivision.y;
    vec3 prim_verts[3];
    build_prim_verts ( prim_id, prim_verts );

    uint key = subdivision.x;
    vec3 key_verts[3];
    build_key_verts ( key, prim_verts, key_verts );

    key_verts[0].y = field_height ( key_verts[0].x, key_verts[0].z );
    key_verts[1].y = field_height ( key_verts[1].x, key_verts[1].z );
    key_verts[2].y = field_height ( key_verts[2].x, key_verts[2].z );

    // TODO move planes to world space instead?
    key_verts[0] = ( frame_uniforms.view_from_world * vec4 ( key_verts[0], 1 ) ).xyz;
    key_verts[1] = ( frame_uniforms.view_from_world * vec4 ( key_verts[1], 1 ) ).xyz;
    key_verts[2] = ( frame_uniforms.view_from_world * vec4 ( key_verts[2], 1 ) ).xyz;

#if 1
    for ( uint i = 0; i < 6; ++i ) {
        bool outside = true;
        for ( uint j = 0; j < 3; ++j ) {
            float d = dot ( vec4 ( key_verts[j], 1 ), frame_uniforms.frustum_planes[i] );
            outside = outside && d < 0;
        }
        
        if ( outside ) {
            return false;
        }
    }

    return true;
#endif

    // simple inside test (code from zeux blog). slightly slower than outside test when tested
#if 0
    for ( uint i = 0; i < 6; ++i ) {
        bool inside = false;

        for ( uint j = 0; j < 3; ++j ) {
            if ( dot ( vec4 ( key_verts[j], 1 ), frame_uniforms.frustum_planes[i] ) > 0 ) {
                inside = true;
                break;
            }
        }

        if ( !inside ) {
            return false;
        }
    }
    return true;
#endif

    // gpu zen 2 source code impl. a bit slower when tested
#if 0
    bool inside = true;
    vec3 aabb_min = vec3 (  10e6 );
    vec3 aabb_max = vec3 ( -10e6 );
    aabb_min = min ( aabb_min, key_verts[0].xyz );
    aabb_min = min ( aabb_min, key_verts[1].xyz );
    aabb_min = min ( aabb_min, key_verts[2].xyz );
    aabb_max = max ( aabb_max, key_verts[0].xyz );
    aabb_max = max ( aabb_max, key_verts[1].xyz );
    aabb_max = max ( aabb_max, key_verts[2].xyz );
    for ( uint i = 0; i < 6; ++i ) {
        bvec3 b = greaterThan ( frame_uniforms.frustum_planes[i].xyz, vec3 ( 0 ) );
        vec3 n = mix ( aabb_min, aabb_max, b );
        inside = inside && ( dot ( vec4 ( n, 1.0 ), frame_uniforms.frustum_planes[i] ) >= 0 );
    }
    return inside;
#endif
}

void write_subdivision ( uvec2 subdivision ) {
    // TODO store capacity in subdivision buffer and test against that to prevent overflow crashes
    uint idx = atomicAdd ( subdivision_buffer.count, 1 );
    subdivision_buffer.data[idx] = subdivision;
    
    if ( cull_subdivision ( subdivision ) ) {
        uint cull_idx = atomicAdd ( culled_subdivision_buffer.count, 1 );
        culled_subdivision_buffer.data[cull_idx] = subdivision;
    }
}

void update_subdivision ( uvec2 subdivision, int target_lod ) {
    uint key = subdivision.x;
    int key_lod = findMSB ( key );

    uint prim_id = subdivision.y;
    if ( key_lod < target_lod && !is_leaf_key ( key ) ) {
        // subdivide
        uvec2 children_keys = make_children_keys ( key );
        write_subdivision ( uvec2 ( children_keys.x, prim_id ) );
        write_subdivision ( uvec2 ( children_keys.y, prim_id ) );
    } else if ( key_lod == target_lod ) {
        // keep
        write_subdivision ( uvec2 ( key, prim_id ) );
    } else {
        // want to merge...
        if ( is_root_key ( key ) ) {
            // can't, keep
            write_subdivision ( uvec2 ( key, prim_id ) );
        } else if ( is_child_zero_key ( key ) ) {
            // merge
            uint parent_key = make_parent_key ( key );
            write_subdivision ( uvec2 ( parent_key, prim_id ) );
        }
    }
}

layout ( local_size_x = 64, local_size_y = 1, local_size_z = 1 ) in;
void main ( void ) {
    uint thread_id = gl_GlobalInvocationID.x;
    if ( thread_id >= prev_subdivision_buffer.count ) {
        return;
    }
    uvec2 subdivision = prev_subdivision_buffer.data[thread_id];

    uint prim_id = subdivision.y;
    vec3 prim_verts[3];
    build_prim_verts ( prim_id, prim_verts );

    //uint key = subdivision.x;
    //vec3 key_verts[3];
    //build_key_verts ( key, prim_verts, key_verts );

    // TODO
    //  ref impl uses key_verts instead of prim_verts here, which is right? 
    float distance_to_camera = distance ( ( prim_verts[1] + prim_verts[2] ) / 2.0, frame_uniforms.cam_world_pos );
    int target_lod = int ( compute_lod ( subdivision, distance_to_camera, distance ( prim_verts[0], prim_verts[1] ) ) );

    update_subdivision ( subdivision, target_lod );
}
