#version 450

#include "xs.glsl"

layout ( binding = 0, set = xs_shader_binding_set_dispatch_m, rgba8 ) uniform writeonly image2D frame_image;

layout ( local_size_x = 1, local_size_y = 1, local_size_z = 1 ) in;

void main() {
    ivec2 pixel_coord = ivec2 ( gl_WorkGroupID.xy );
    vec3 color = vec3 ( 0, 1, 0 );
    vec4 store_value = vec4 ( color, 1 );
    imageStore ( frame_image, pixel_coord, store_value );
}
